# Generated by Django 4.2.2 on 2023-06-15 17:38

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_remove_todo_tag_todo_tags_alter_tag_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todo',
            name='time_stamp',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
