# Generated by Django 4.2.2 on 2023-06-15 20:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_alter_todo_time_stamp'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='todo',
            name='tags',
        ),
        migrations.DeleteModel(
            name='Tag',
        ),
        migrations.AddField(
            model_name='todo',
            name='tags',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
    ]
